services:
  postgres:
    build:
      context: ./.docker/postgres
      dockerfile: Dockerfile
    restart: unless-stopped
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/home/postgres/pgdata/data
    networks:
      - internal
networks:
  internal:
    driver: bridge

volumes:
  postgres_data: