services:
  postgres:
    build:
      context: ./.docker/postgres
      dockerfile: Dockerfile
    restart: unless-stopped
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/home/postgres/pgdata/data
    networks:
      - internal
  auth:
    build:
      context: ./
      dockerfile: services/auth/Dockerfile
    restart: unless-stopped

    env_file:
      - .env
    environment:
      DB_HOST : postgres
      APP_MODE: production
    ports:
      - "4000:4000"
    networks:
      - internal
    depends_on:
      postgres:
        condition: service_healthy

networks:
  internal:
    driver: bridge

volumes:
  postgres_data: